apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.rbac.serviceAccountName }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{ else }}
      serviceAccountName: {{ .Release.Name }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env.global }}
            - name: {{ $key  }}
              value: {{ $val | quote }}
            {{- end }}

            {{- if .Values.env.local.CH_KUBE_IMPORTER_RESOURCE_URL }}
            - name: CH_KUBE_IMPORTER_RESOURCE_URL
              value: "{{ .Values.env.local.CH_KUBE_IMPORTER_RESOURCE_URL }}"
            {{- else }}
            - name: CH_KUBE_IMPORTER_RESOURCE_URL
              value: "{{ .Release.Name }}-resource:1213"
            {{- end }}

            {{- if .Values.env.local.CH_KUBE_IMPORTER_PERMISSIONS_URL }}
            - name: CH_KUBE_IMPORTER_PERMISSIONS_URL
              value: "{{ .Values.env.local.CH_KUBE_IMPORTER_PERMISSIONS_URL }}"
            {{- else }}
            - name: CH_KUBE_IMPORTER_PERMISSIONS_URL
              value: "{{ .Release.Name }}-permissions:4242"
            {{- end }}

            {{- if .Values.env.local.CH_KUBE_IMPORTER_VOLUMES_URL }}
            - name: CH_KUBE_IMPORTER_VOLUMES_URL
              value: "{{ .Values.env.local.CH_KUBE_IMPORTER_VOLUMES_URL }}"
            {{- else }}
            - name: CH_KUBE_IMPORTER_VOLUMES_URL
              value: "{{ .Release.Name }}-volume:4343"
            {{- end }}

      {{- with .Values.image.secret }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
