# File for noice errors generation

Name = "kierrors"
SID = "Kube-Importer"

# errors

#resources errors
[[error]]
    Name = "ErrUnableExportResources"
    StatusHTTP = 500
    Message = "Unable to export resources from Kubernetes"
    Kind = 1

[[error]]
    Name = "ErrUnableImportResources"
    StatusHTTP = 500
    Message = "Unable to import resources"
    Kind = 2

[[error]]
    Name = "ErrInternalError"
    StatusHTTP = 500
    Message = "Internal error"
    Kind = 3

[[error]]
    Name = "ErrAdminRequired"
    StatusHTTP = 403
    Message = "Admin access required"
    Kind = 4