replicaCount: 1

image:
  repository: containerum/kube-importer
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 1666
  targetPort: 1666
  externalIP:

rbac:
  serviceAccountName: null

env:
  global:
    DEBUG: "true"
    TEXTLOG: "true"
    CORS: "false"
    EXCLUDED_NS: "default,kube-system"
  local:
    RESOURCE_URL: "http://resource:1213"
    PERMISSIONS_URL: "http://permissions:4242"
    VOLUMES_URL: "http://volume:4343"
